### ISSUE TITLE
Bad zip file error - pygraphviz-1.7-cp38-cp38-win_amd64.whl

### ISSUE THREAD

**Issue by sreedat** [CristiFati/Prebuilt-Binaries#1] opened 2021-08-06 01:29 UTC
Hi I have downloaded the "pygraphviz-1.7-cp38-cp38-win_amd64.whl" (thank you for providing these files by the way) and tried to install the file using "pip install pygraphviz-1.7-cp38-cp38-win_amd64.whl" and I get the following error (I have tried to download multiple times and tried the installation with each one but the error persists)

I'm installing this into an environment on Anaconda. I have already installed 64-bit Graphviz for Windows-10 and added it to my path. I'm installing the "whl" file from the exact file location where I have downloaded it to.

```
(pomgn) C:\Users\sreedatta>pip install C:\Users\sreedatta\pygraphviz-1.7-cp38-cp38-win_amd64.whl

Processing c:\users\sreedatta\pygraphviz-1.7-cp38-cp38-win_amd64.whl
ERROR: Exception:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\pomgn\lib\site-packages\pip\_internal\cli\base_command.py", line 173, in _main
    status = self.run(options, args)
  File "C:\ProgramData\Anaconda3\envs\pomgn\lib\site-packages\pip\_internal\cli\req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "C:\ProgramData\Anaconda3\envs\pomgn\lib\site-packages\pip\_internal\commands\install.py", line 315, in run
    requirement_set = resolver.resolve(
  File "C:\ProgramData\Anaconda3\envs\pomgn\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 75, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "C:\ProgramData\Anaconda3\envs\pomgn\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 471, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "C:\ProgramData\Anaconda3\envs\pomgn\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 433, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "C:\ProgramData\Anaconda3\envs\pomgn\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 204, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\ProgramData\Anaconda3\envs\pomgn\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 295, in __init__
    super().__init__(
  File "C:\ProgramData\Anaconda3\envs\pomgn\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "C:\ProgramData\Anaconda3\envs\pomgn\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 227, in _prepare
    dist = self._prepare_distribution()
  File "C:\ProgramData\Anaconda3\envs\pomgn\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 305, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "C:\ProgramData\Anaconda3\envs\pomgn\lib\site-packages\pip\_internal\operations\prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\ProgramData\Anaconda3\envs\pomgn\lib\site-packages\pip\_internal\operations\prepare.py", line 570, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "C:\ProgramData\Anaconda3\envs\pomgn\lib\site-packages\pip\_internal\operations\prepare.py", line 61, in _get_prepared_distribution
    return abstract_dist.get_pkg_resources_distribution()
  File "C:\ProgramData\Anaconda3\envs\pomgn\lib\site-packages\pip\_internal\distributions\wheel.py", line 26, in get_pkg_resources_distribution
    with ZipFile(self.req.local_file_path, allowZip64=True) as z:
  File "C:\ProgramData\Anaconda3\envs\pomgn\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "C:\ProgramData\Anaconda3\envs\pomgn\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```
What am I doing wrong? Can you help?

**Comment by CristiFati** [comment] 2021-10-13 07:28
Thank you @sreedat for submitting this issue, and sorry for the long pause (I missed the issue :( ).

Could you provide the size of the file that you downloaded (*C:\\Users\\sreedatta\\pygraphviz-1.7-cp38-cp38-win\_amd64.whl*)?
Cause it's working OK on my side.

**Comment by CristiFati** [comment] 2021-12-08 11:19
@sreedat: I think it might have something to do with the *LFS* switch (https://www.atlassian.com/git/tutorials/git-lfs). Could you please check whether it still reproduces?

**Comment by ZachL1** [comment] 2022-01-21 09:57
I had the same problem!

**Comment by ZachL1** [comment] 2022-01-22 09:12
I have solved the problem and it seems to be caused by a corrupt `.whl` file.
You can re-download the `.whl` file and try again. @sreedat

**Comment by CristiFati** [comment] 2022-04-11 06:12
It has been 5+ months since I requested for details that never came, so I'm assuming the problem is no longer reproducible.

Closing, please reopen if it pops up again.

**Closed as completed by CristiFati** 2022-04-11 06:12 UTC
